# References: 
# http://karunsubramanian.com/uncategorized/creating-a-distributed-service-using-docker-a-beginners-guide/
# https://docs.docker.com/get-started/08_using_compose/

version: '3'
services:
  poll1:
    build:
      context: .
      dockerfile: Dockerfile_poll1
    ports:
      - "12345:12345" #this is for broadcast
      - "5007:5007/udp"  # This is for the multicast
  poll2:
    build:
      context: .
      dockerfile: Dockerfile_poll2  # Use Dockerfile_master if the setup is the same
    ports:
      - "12346:12345"  # Use different external port
      - "5008:5007/udp"  # Use different external port for multicast, if needed

  node1:
    build:
      context: .
      dockerfile: Dockerfile_node
    depends_on:
      - poll1
      - poll2

  node2:
    build:
      context: .
      dockerfile: Dockerfile_node
    depends_on:
      - poll1
      - poll2

  node3:
    build:
      context: .
      dockerfile: Dockerfile_node
    depends_on:
      - poll1
      - poll2

  node4:
    build:
      context: .
      dockerfile: Dockerfile_node
    depends_on:
      - poll1
      - poll2

  node5:
    build:
      context: .
      dockerfile: Dockerfile_node
    depends_on:
      - poll1
      - poll2

  node6:
    build:
      context: .
      dockerfile: Dockerfile_node
    depends_on:
      - poll1
      - poll2
