# Reference: http://karunsubramanian.com/uncategorized/creating-a-distributed-service-using-docker-a-beginners-guide/

version: '3'
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile_master
    ports:
      - "12345:12345" #this is for broadcast
      - "5007:5007/udp"  # This is for the multicast

  client1:
    build:
      context: .
      dockerfile: Dockerfile_client
    depends_on:
      - master

  client2:
    build:
      context: .
      dockerfile: Dockerfile_client
    depends_on:
      - master

  client3:
    build:
      context: .
      dockerfile: Dockerfile_client
    depends_on:
      - master

  client4:
    build:
      context: .
      dockerfile: Dockerfile_client
    depends_on:
      - master
